<?php
/**
 * Apiv1editfail2banAttrTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MailCow
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * mailcow API
 *
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MailCow;

/**
 * Apiv1editfail2banAttrTest Class Doc Comment
 *
 * @category    Class
 * @description array containing the fail2ban settings
 * @package     MailCow
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Apiv1editfail2banAttrTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Apiv1editfail2banAttr"
     */
    public function testApiv1editfail2banAttr()
    {
    }

    /**
     * Test attribute "backlist"
     */
    public function testPropertyBacklist()
    {
    }

    /**
     * Test attribute "ban_time"
     */
    public function testPropertyBanTime()
    {
    }

    /**
     * Test attribute "max_attempts"
     */
    public function testPropertyMaxAttempts()
    {
    }

    /**
     * Test attribute "netban_ipv4"
     */
    public function testPropertyNetbanIpv4()
    {
    }

    /**
     * Test attribute "netban_ipv6"
     */
    public function testPropertyNetbanIpv6()
    {
    }

    /**
     * Test attribute "retry_window"
     */
    public function testPropertyRetryWindow()
    {
    }

    /**
     * Test attribute "whitelist"
     */
    public function testPropertyWhitelist()
    {
    }
}
