<?php
/**
 * MailboxesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MailCow
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * mailcow API
 *
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace MailCow;

use MailCow\Configuration;
use MailCow\ApiException;
use MailCow\ObjectSerializer;

/**
 * MailboxesApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailCow
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MailboxesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMailbox
     *
     * Create mailbox.
     *
     */
    public function testCreateMailbox()
    {
    }

    /**
     * Test case for deleteMailbox
     *
     * Delete mailbox.
     *
     */
    public function testDeleteMailbox()
    {
    }

    /**
     * Test case for deleteMailboxTags
     *
     * Delete mailbox tags.
     *
     */
    public function testDeleteMailboxTags()
    {
    }

    /**
     * Test case for editMailboxSpamFilterScore
     *
     * Edit mailbox spam filter score.
     *
     */
    public function testEditMailboxSpamFilterScore()
    {
    }

    /**
     * Test case for getMailboxes
     *
     * Get mailboxes.
     *
     */
    public function testGetMailboxes()
    {
    }

    /**
     * Test case for quarantineNotifications
     *
     * Quarantine Notifications.
     *
     */
    public function testQuarantineNotifications()
    {
    }

    /**
     * Test case for updateMailbox
     *
     * Update mailbox.
     *
     */
    public function testUpdateMailbox()
    {
    }

    /**
     * Test case for updateMailboxACL
     *
     * Update mailbox ACL.
     *
     */
    public function testUpdateMailboxACL()
    {
    }

    /**
     * Test case for updatePushoverSettings
     *
     * Update Pushover settings.
     *
     */
    public function testUpdatePushoverSettings()
    {
    }
}
