<?php
/**
 * MailboxesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  MailCow
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mailcow API
 *
 * mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MailCow\Test\Api;

use \MailCow\Configuration;
use \MailCow\ApiException;
use \MailCow\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MailboxesApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailCow
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MailboxesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createMailbox
     *
     * Create mailbox.
     *
     */
    public function testCreateMailbox()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteMailbox
     *
     * Delete mailbox.
     *
     */
    public function testDeleteMailbox()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteMailboxTags
     *
     * Delete mailbox tags.
     *
     */
    public function testDeleteMailboxTags()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editMailboxSpamFilterScore
     *
     * Edit mailbox spam filter score.
     *
     */
    public function testEditMailboxSpamFilterScore()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMailboxes
     *
     * Get mailboxes.
     *
     */
    public function testGetMailboxes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quarantineNotifications
     *
     * Quarantine Notifications.
     *
     */
    public function testQuarantineNotifications()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMailbox
     *
     * Update mailbox.
     *
     */
    public function testUpdateMailbox()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMailboxACL
     *
     * Update mailbox ACL.
     *
     */
    public function testUpdateMailboxACL()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePushoverSettings
     *
     * Update Pushover settings.
     *
     */
    public function testUpdatePushoverSettings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
